#!/bin/bash

folders=(${1:-data})

# Setup
for folder in ${folders[@]}
do
	read -t 2 -p "Remove Folder ${folder} ?   [Y/n]  " yn
	if [[ "${yn}" =~ ^[Yy]$ ]] || ( [[ -z $yn ]] )
	then
		rm -rf ${folder}
	else
		continue
	fi
	echo

done
